[package]
name = "uefi-div-bug"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
log = "0.4"
uefi = "0.11.0"
uefi-services = "0.8.0"
